
   export const Data = [
        {id:1,time:"9:00 A.M.",stage:"WEST STAGE",keynote:"OPENING KEYNOTE",title:"Powering growth for the internet economy",info:"Stripe’s mission to grow the GDP of the internet means more than just helping companies do business online: now more than ever, we’re focused on helping our customers grow revenue and reduce costs in the face of mounting economic uncertainty. Join Stripe cofounder and CEO Patrick Collison and other Stripe leaders for a discussion of how Stripe is helping users accelerate their growth."},

        {id:2,time:"10:30 A.M.",stage:"WEST STAGE",keynote:"PANEL DISCUSSION",title:"How successful startups are growing in the current market",info:"Startups are facing a shifting market landscape, increasingly feeling the need to do more with less. Join a panel of high-growth founders and other experts as they discuss how they’re managing runway (and minimizing burn), building products with a leaner team, maintaining company morale, and more."},

        {id:3,time:"10:30 A.M.",stage:"EAST STAGE",keynote:"PANEL DISCUSSION",title:"Removing barriers to enterprise innovation",info:"Experimenting with new ideas, changing course, and being prepared for the unexpected all become harder the bigger an organization gets. Hear enterprise executives discuss how they’ve overcome challenges like institutional risk aversion, brittle systems, and a bias toward the status quo to foster an innovative culture."},

        {id:4,time:"11:30 A.M.",stage:"WEST STAGE",keynote:"BREAKOUT TALK",title:"Modernize your finance stack and avoid leaving money on the table",info:"Buyers of all types are cutting back on spending, meaning businesses need to acquire, retain, and grow reliable recurring revenue—while lowering costs—to weather the storm. Join us as we discuss where you may be leaving money on the table, and get practical tips to grow recurring revenue and streamline your finance processes."},

        {id:5,time:"11:30 A.M.",stage:"EAST STAGE",keynote:"PANEL DISCUSSION",title:"What’s happening in fintech—banking-as-a-service, compliance, and new revenue models",info:"Join our panel of experts for a discussion of the ups and downs in fintech over the past year, the impact new offerings will have on the overall financial services landscape, and the emerging trends we’re watching (and building for) next."},

        {id:6,time:"12:45 P.M.",stage:"EAST STAGE",keynote:"BREAKOUT TALK",title:"What’s next for platform payments?",info:"The gig economy, the on-demand economy, the creator economy: each of these was made possible by multi-party payments infrastructure for routing funds between a buyer and a seller. What economy comes next? Hear from Stripe experts on the future of platform payments, including how new use cases are guiding our own roadmap."},

        {id:7,time:"12:45 P.M.",stage:"WEST STAGE",keynote:"BREAKOUT TALK",title:"Why payments experience is customer experience",info:"Payments are core to your customer experience, from offering the right payment methods to preventing fraud and false declines. Hear from Stripe experts about the latest trends in consumer payments, and how you can build a payments experience that increases revenue and drives brand loyalty."},

        {id:8,time:"1:45 P.M.",stage:"WEST STAGE",keynote:"PANEL DISCUSSION",title:"CFO roundtable on navigating change in 2023",info:"Join finance leaders for a discussion on the evolving role of CFOs and the finance function. From managing financial operations to shaping a company's growth strategies, learn how these experts are navigating operational resiliency, digital transformation, and risk management in today's unpredictable business landscape."},

        {id:9,time:"1:45 P.M.",stage:"EAST STAGE",keynote:"PANEL DISCUSSION",title:"Accelerating product development in the age of AI",info:"Artificial intelligence is fast becoming a generation-defining technological breakthrough. Join a panel of technology and product leaders for a discussion about the role of AI in product development, including lessons learned from past technological milestones, how to determine promising AI use cases, and finding a balance between quick fixes and long-term investments."},

        {id:10,time:"3:00 P.M. ",stage:"WEST STAGE",keynote:"FIRESIDE CHAT",title:"Fireside chat with Sam Altman",info:"Join us for a conversation with OpenAI CEO Sam Altman. We’ll discuss the future of AI and why technological progress is key to achieving real, sustainable economic growth."} 
    ]
